name: Release
on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip component
        run: cd custom_components/tesira_forte && zip -r tesira_forte.zip ./
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: custom_components/tesira_forte/tesira_forte.zip
